# 这个 GitHub Action 的名字是 "Update the main branch README profile page with a script"
name: Update the main branch README profile page with a script

# 触发条件：
on:
  # 当有新的 push 操作时触发
  push:
  # 我在使用 GitHub CLI （gh） 允许手动触发工作流
  # gh workflow run update-readme
  workflow_dispatch:
  # 当有新的 pull request 操作时触发
  pull_request:
  schedule: 
    # Runs on the 8, 10, 14 and 16th hour.
    # - cron: "0 8-11/5,14-17/4 * * *"
    # Runs at 00:00 UTC every day.
    - cron: "0 0 * * *"
    # - cron: "0 */8 * * *"

# 在触发后，会运行一个名为 "markscribe" 的 job，该 job 在 Ubuntu 系统最新版上运行。
jobs:
  markscribe:
    runs-on: ubuntu-latest

    # 这个 job 有三个步骤：
    steps:
      # 使用 actions/checkout@main 操作，将项目代码库克隆到工作区。
      - uses: actions/checkout@main

      # 使用 muesli/readme-scribe@master 操作，使用指定的模板生成 README 文件，并将其写入到项目的根目录中。
      - uses: muesli/readme-scribe@master
        # 使用者提供的令牌，可以让 Action 访问使用者在 GitHub 上的私有数据。
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
      # 使用 stefanzweifel/git-auto-commit-action@v4 操作，将生成的 README 文件提交到项目的 "main" 分支，并使用指定的用户名和邮箱记录提交记录。
      - uses: stefanzweifel/git-auto-commit-action@v4
        # 使用者提供的令牌，可以让 Action 访问使用者在 GitHub 上的私有数据。
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: cubxxw
          commit_user_email: 3293172751nss@gmail.com
          commit_author: cubxxw 🤖 <3293172751nss@gmail.com>
          
      # 运行一系列 shell 命令，配置本地 Git 设置，从远程库拉取最新版本并推送到远程库。
      - name: Auto green
        run: |
          git config --local user.email "3293172751nss@gmail.com"
          git config --local user.name "cubxxw"
          git remote set-url origin https://${{ secrets.BOT_GITHUB_TOKEN }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          # 将 UTC 时间转换为上海时间
          local_time=$(date -u -d "$(date -u)" "+%Y-%m-%d %H:%M:%S" -d "8 hours")
          echo " 🚀 Shanghai time of last status update by the bot <a href='https://github.com/kubbot'>@kubbot</a>: $local_time" >> README.md
          # 允许空提交，-a 省略git add . 而且设置签名
          git commit --allow-empty -a -s -m "🌟 You never lose, either you win or you learn! 💪"
          git push
# env
# GITHUB_TOKEN：这是一个自动生成的令牌，可以让 Action 访问项目的数据。
# PERSONAL_GITHUB_TOKEN：这是一个使用者提供的令牌，可以让 Action 访问使用者在 GitHub 上的私有数据。
